image: ubuntu:18.10

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get -qq update > /dev/null 2>&1
  - apt-get install -y build-essential linux-virtual

build:
  except:
    - tags
  script:
    - make clean
    - make
